### ISSUE TITLE
Product Group

### ISSUE THREAD

**Issue by asaglam76** [a1telekom/ra-risk-coverage#3]
Hi, how can I add product group?

Before I go on working, is this only a concept or a very limited tool?. It looks like that it ismore alpha because you're not able to add users and so on. It runs only in dev instance and not in production.

Best regards

**Comment by krokce** [comment]
There is no UI for many low-level configuration tasks like adding tenants, product groups, LoBs and even business processes. All those are initially pre-configured and if needed can be defined to fit your organization with adding/changing the values directly in the respective reference tables in the DB when you first configure the environment. 

Yes, this is indeed very limited tool intended for modeling typical CSP/Telecom risk environment. I would not recommend you go on working without having basic knowledge of telecom processes, SQL and Node.js skills. 

In addition note that this is shared under MIT license so no warranties or support come with it. Reporting Bugs and Feature requests  are very welcome, but please use the provided templates when you create a new issue.
