### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by BaizaSajjad** [a1telekom/ra-risk-coverage#6]
Hi. I have been able to sign in to the webpage. For a while, it was working fine but now I'm getting the following error:
localhost is not responding to a long-running script

**Comment by BaizaSajjad** [comment]
Also, any changes that I make on MySQL tag database or on the front end webpage, it doesn't reflect those changes.
Could you help me troubleshoot this?
Thanks

**Comment by krokce** [comment]
Hi, did you manage to solve the issues above? If not, see my comments below:

- if you are using IE you may experience your first error. Note that IE is not supported by most of the JS libraries used in this project, so if possible use another browser

- any changes you do in the code-base or database must be immediately visible for you. If you are making changes in the code - most likely you forgot to restart the node.js server after making the changes. If you are running the dev. environment using `grunt serve` this restart should happen automatically, if not you may want to restart node after making changes in the code. You can consider using `grunt` or maybe [forever](https://github.com/nodejitsu/forever) module to do this automatically

**Comment by krokce** [comment]
Considering the issue closed

**Comment by BaizaSajjad** [comment]
> Hi, did you manage to solve the issues above? If not, see my comments below:
> 
> * if you are using IE you may experience your first error. Note that IE is not supported by most of the JS libraries used in this project, so if possible use another browser
> * any changes you do in the code-base or database must be immediately visible for you. If you are making changes in the code - most likely you forgot to restart the node.js server after making the changes. If you are running the dev. environment using `grunt serve` this restart should happen automatically, if not you may want to restart node after making changes in the code. You can consider using `grunt` or maybe [forever](https://github.com/nodejitsu/forever) module to do this automatically

Hi,
How do I restart the node.js server. Any commands for that?

**Comment by BaizaSajjad** [comment]
Everytime I wish to open the software, I run grunt serve command and the page automatically opens in IE. Is this the way to do this?

**Comment by krokce** [comment]
Yes, running `grunt serve` is fully ok use for development. It will launch your default browser and even automatically restart node.js whenever you change the code. Note that, you should try using another browser (e.g. Firefox, Chrome etc.) by pasting the same url that you get in IE (http://localhost:9000), or consider changing your default browser.

You can always stop the server with `Ctrl+C` in the console where it is running and restart again. 

For production you can consider using [pm2](https://pm2.keymetrics.io/)

**Comment by BaizaSajjad** [comment]
Hi.
While creating a dataflow: System--Interface--Datasources--Procedures--Schedulers,
in procedure info for a control, where is the control type (e.g reconciliation) logic defined?

**Comment by krokce** [comment]
The **Dataflow** is used to document and define the dependencies between objects used for building a control and from there link to the **Risk coverage model**, which is the main purpose of this. Unfortunately, apart from control type and brief description and some general control information, no more details about the control logic are expected here.  
The very logic of the control is supposed to be defined in the whatever platform the control(s) are developed and running.

**Comment by teragotti** [comment]
> 
> 
> Hi.
> While creating a dataflow: System--Interface--Datasources--Procedures--Schedulers,
> in procedure info for a control, where is the control type (e.g reconciliation) logic defined?

We have decided to stop the detail of documentation in the dataflow at this point. The exact reconciliation logic is defined in your processing engine where you 'execute' that control.
This could be a manual process but ideally an automated process running either within standard software or selfdeveloped toolset. As you can use different tools and methods to execute a control you would have to put some effort in keeping the logic in sync with the dataflow especilly when reconcilliation logic changes over time. 
So consider the definition of a control in the dataflow as a pointer to the control definition in your processing engine(s).
